### ISSUE TITLE
Shouldn't cd to ~/files

### ISSUE THREAD

**Issue by andrewsali** [nuvolos-cloud/r-nuvolos-tools#1]
I think this cd is incorrect, we set the install location in via the cluster path, so it's not needed. However it actually blocks the command from executing if BEEGFSHOME/files does not exist.

https://github.com/nuvolos-cloud/r-nuvolos-tools/blob/27065419888146d1c3ed85e62e00aec2f10f8aa8/R/package_sync_hpc.R#L26

**Comment by matek-alphacruncher** [comment]
We now set the HOME everywhere before referring to '~'.
